### ISSUE TITLE
Release assets should be always uploaded

### ISSUE THREAD

**Issue by dwenegar** [xoofx/dotnet-releaser#45]
`UpdateChangelogAndUploadPackages` doesn't upload a new release asset if an old one with the same name is already attached to a release.

While implementing #37, I noticed that the new asset and the old asset have different hashes.
This breaks generating the scoop manifest since the manifest is updated using the asset of the new asset.

**Comment by xoofx** [comment]
The problem is how to detect that the asset hasn't changed? Usually if I need to reupload a release, I delete it entirely and manually.
It is the same for homebrew, the assets have to be generated at the same time. You could add an option to force update the assets maybe and to fail if this option is not set and assets already exists?

**Comment by dwenegar** [comment]
> You could add an option to force update the assets maybe and to fail if this option is not set and assets already exists?

I'll do this
