### ISSUE TITLE
Feature request: GitHub action

### ISSUE THREAD

**Issue by humble-barnacle001** [xoofx/dotnet-releaser#6]
Please could you consider releasing this as a GitHub action that can be leveraged in workflows?

**Comment by xoofx** [comment]
So I have considered it, but I'm not sure it will be worth the investment.

I'm already using it in GitHub Action and I made an entry in the documentation here [Adding dotnet-releaser to your CI on GitHub](https://github.com/xoofx/dotnet-releaser/tree/main/doc#3-adding-dotnet-releaser-to-your-ci-on-github)

Because `dotnet-releaser` requires that you install .NET 6+ anyway but also in order to build and package your projects, it means that once you have installed the dotnet SDK in a GitHub action, `dotnet-releaser` can be run very easily in 2 lines:

```sh
dotnet tool install --global dotnet-releaser --version "0.1.*"
dotnet-releaser publish --nuget-token ${{secrets.NUGET_TOKEN}} --github-token ${{secrets.TOKEN_GITHUB}} src/dotnet-releaser.toml
```

This is what I'm actually [already using in grpc-curl](https://github.com/xoofx/grpc-curl/blob/329ac4fce0c7840fbca63c0b66400fc24bce3791/.github/workflows/ci.yml#L46-L47)

**Comment by humble-barnacle001** [comment]
Thanks, I had not seen the doc folder, could you also please mention it on the main README

**Comment by xoofx** [comment]
> Thanks, I had not seen the doc folder, could you also please mention it on the main README

Yep, done 👍
